### ISSUE TITLE
MyQ is giving connection errors

### ISSUE THREAD

**Issue by rnile** [Goose66/myq-polyglotv2#12]
At first the errors indicated the token has expired, but I'm not sure how to re-create.  
2021-09-01 15:25:04,188 Controller polyinterface      WARNING  myqapi:_call_api: Network/server error in HTTP POST in _call_api(): 400 Client Error: Bad Request for url: https://api.myqdevice.com/api/v5/Login
2021-09-01 15:25:04,667 Controller polyinterface      ERROR    myqapi:getDeviceList: There was an authentication error with the MyQ account: 401.101 - Unauthorized: The Security Token has expired.

I stopped the service and even changed the MyQ password.   Now it looks a little different when I restart, but still no connection:
2021-09-01 15:25:52,076 NodeServer polyinterface      DEBUG    myqapi:loginToService: in API loginToService()...
2021-09-01 15:25:52,663 NodeServer polyinterface      WARNING  myqapi:_call_api: Network/server error in HTTP POST in _call_api(): 400 Client Error: Bad Request for url: https://api.myqdevice.com/api/v5/Login
2021-09-01 15:25:52,664 NodeServer polyinterface      INFO     polyinterface:addNotice: Sending addnotice to Polyglot: {'key': 'login_error', 'value': 'There was an error connecting to the MyQ service. Please check the log files and correct the issue before restarting the nodeserver.'}
2021-09-01 15:25:52,667 NodeServer polyinterface      INFO     myq-poly:stopMe: Asking Polyglot to stop me.
2021-09-01 15:25:52,781 MQTT       polyinterface      DEBUG    polyinterface:_message: Received stop from Polyglot... Shutting Down.
2021-09-01 15:25:52,782 MQTT       polyinterface      INFO     polyinterface:stop: Disconnecting from MQTT... localhost:1883
2021-09-01 15:25:52,784 MQTT       polyinterface      INFO     polyinterface:reportDriver: Updating Driver controller - ST: 0, uom: 2
2021-09-01 15:25:52,787 MQTT       polyinterface      INFO     polyinterface:_disconnect: MQTT Graceful disconnection.
2021-09-01 15:25:52,788 MQTT       polyinterface      DEBUG    polyinterface:_startMqtt: MQTT Done:
2021-09-01 15:29:52,771 MainThread polyinterface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2021-09-01 15:29:53,534 MainThread polyinterface      INFO     polyinterface:init_interface: Received Config from STDIN.
2021-09-01 15:29:53,536 MainThread polyinterface      INFO     __init__:<module>: UDI Polyglot v2 Interface 2.1.0 Starting...
2021-09-01 15:29:53,894 MainThread polyinterface      DEBUG    polyinterface:get_network_interface: gws: {'default': {2: ('192.168.1.1', 'eth0')}, 2: [('192.168.1.1', 'eth0', True)]}
2021-09-01 15:29:53,895 MainThread polyinterface      DEBUG    polyinterface:get_network_interface: gw: default=('192.168.1.1', 'eth0')
2021-09-01 15:29:53,896 MainThread polyinterface      DEBUG    polyinterface:get_network_interface: ifad: eth0=[{'addr': '192.168.1.10', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}]
2021-09-01 15:29:53,897 MainThread polyinterface      INFO     polyinterface:__init__: Connect: Network Interface: {'addr': '192.168.1.10', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}
2021-09-01 15:29:53,898 Interface  polyinterface      INFO     polyinterface:_startMqtt: Connecting to MQTT... localhost:1883
2021-09-01 15:29:53,981 MQTT       polyinterface      INFO     polyinterface:_connect: MQTT Connected with result code 0 (Success)
2021-09-01 15:29:53,983 MQTT       polyinterface      INFO     polyinterface:_connect: MQTT Subscribing to topic: udi/polyglot/ns/5 -  MID: 1 Result: 0
2021-09-01 15:29:53,984 MQTT       polyinterface      INFO     polyinterface:_connect: MQTT Subscribing to topic: udi/polyglot/connections/polyglot -  MID: 2 Result: 0
2021-09-01 15:29:53,985 MQTT       polyinterface      INFO     polyinterface:_connect: Sent Connected message to Polyglot
2021-09-01 15:29:53,990 MQTT       polyinterface      INFO     polyinterface:_subscribe: MQTT Subscribed Succesfully for Message ID: 1 - QoS: (0,)
2021-09-01 15:29:53,995 MQTT       polyinterface      INFO     polyinterface:_subscribe: MQTT Subscribed Succesfully for Message ID: 2 - QoS: (0,)
2021-09-01 15:29:54,062 NodeServer polyinterface      INFO     myq-poly:start: Started MyQ Node Server...
2021-09-01 15:29:54,063 NodeServer polyinterface      INFO     polyinterface:removeNotice: Sending removenotice to Polyglot for index {'key': 'login_error'}
2021-09-01 15:29:54,182 NodeServer polyinterface      DEBUG    myqapi:loginToService: in API loginToService()...
2021-09-01 15:29:54,732 NodeServer polyinterface      WARNING  myqapi:_call_api: Network/server error in HTTP POST in _call_api(): 400 Client Error: Bad Request for url: https://api.myqdevice.com/api/v5/Login
2021-09-01 15:29:54,734 NodeServer polyinterface      INFO     polyinterface:addNotice: Sending addnotice to Polyglot: {'key': 'login_error', 'value': 'There was an error connecting to the MyQ service. Please check the log files and correct the issue before restarting the nodeserver.'}
2021-09-01 15:29:54,736 NodeServer polyinterface      INFO     myq-poly:stopMe: Asking Polyglot to stop me.
2021-09-01 15:29:54,787 MQTT       polyinterface      DEBUG    polyinterface:_message: Received stop from Polyglot... Shutting Down.
2021-09-01 15:29:54,788 MQTT       polyinterface      INFO     polyinterface:stop: Disconnecting from MQTT... localhost:1883
2021-09-01 15:29:54,790 MQTT       polyinterface      INFO     polyinterface:reportDriver: Updating Driver controller - ST: 0, uom: 2
2021-09-01 15:29:54,793 MQTT       polyinterface      INFO     polyinterface:_disconnect: MQTT Graceful disconnection.
2021-09-01 15:29:54,795 MQTT       polyinterface      DEBUG    polyinterface:_startMqtt: MQTT Done:

**Comment by jdickensttu** [comment]
Same issue here.

**Comment by psmith3** [comment]
Same here. Looks like the API has changed. Is there any update?

**Comment by pinsonlawrimore** [comment]
Looks like it's being worked on according to this thread (go to latest post): https://forum.universal-devices.com/topic/33494-myq-wont-connect/

**Comment by psmith3** [comment]
> Looks like it's being worked on according to this thread (go to latest post): https://forum.universal-devices.com/topic/33494-myq-wont-connect/

Thank you

**Comment by Goose66** [comment]
New version v2.2.15 is up. Try it and let me know of any errors.

**Comment by jdickensttu** [comment]
Worked first try.  Great work, much appreciated.

**Comment by psmith3** [comment]
Not sure why, but I cannot install from scratch. I also could not get it to update and had to manually remove the MyQ folder from my system. When I try to install it, I get a repo error, but it appears to install. When I add the node server, the config parameters never show up for username and password. Tried manually adding the keys for username and password and I get the following errors. I have tried installing other node servers and did not have an issue and it appears to be just the MyQ. Have you tried a clean install?

> 2021-09-08 05:30:25,264 MainThread polyinterface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
> 2021-09-08 05:30:25,746 MainThread polyinterface      INFO     polyinterface:init_interface: Received Config from STDIN.
> 2021-09-08 05:30:25,747 MainThread polyinterface      INFO     __init__:<module>: UDI Polyglot v2 Interface 2.1.0 Starting...
> 2021-09-08 05:30:26,047 MainThread polyinterface      ERROR    polyinterface:write: Traceback (most recent call last):
> 2021-09-08 05:30:26,048 MainThread polyinterface      ERROR    polyinterface:write: File "./myq-poly.py", line 16, in <module>
> 2021-09-08 05:30:26,048 MainThread polyinterface      ERROR    polyinterface:write: import myqapi as api
> 2021-09-08 05:30:26,049 MainThread polyinterface      ERROR    polyinterface:write: File "/root/.polyglot/nodeservers/MyQ/myqapi.py", line 16, in <module>
> 2021-09-08 05:30:26,049 MainThread polyinterface      ERROR    polyinterface:write: import pkce
> 2021-09-08 05:30:26,050 MainThread polyinterface      ERROR    polyinterface:write: ModuleNotFoundError
> 2021-09-08 05:30:26,050 MainThread polyinterface      ERROR    polyinterface:write: :
> 2021-09-08 05:30:26,050 MainThread polyinterface      ERROR    polyinterface:write: No module named 'pkce'
> 2021-09-08 05:34:36,151 MainThread polyinterface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
> 2021-09-08 05:34:36,505 MainThread polyinterface      INFO     polyinterface:init_interface: Received Config from STDIN.
> 2021-09-08 05:34:36,505 MainThread polyinterface      INFO     __init__:<module>: UDI Polyglot v2 Interface 2.1.0 Starting...
> 2021-09-08 05:34:36,786 MainThread polyinterface      ERROR    polyinterface:write: Traceback (most recent call last):
> 2021-09-08 05:34:36,787 MainThread polyinterface      ERROR    polyinterface:write: File "./myq-poly.py", line 16, in <module>
> 2021-09-08 05:34:36,787 MainThread polyinterface      ERROR    polyinterface:write: import myqapi as api
> 2021-09-08 05:34:36,788 MainThread polyinterface      ERROR    polyinterface:write: File "/root/.polyglot/nodeservers/MyQ/myqapi.py", line 16, in <module>
> 2021-09-08 05:34:36,788 MainThread polyinterface      ERROR    polyinterface:write: import pkce
> 2021-09-08 05:34:36,789 MainThread polyinterface      ERROR    polyinterface:write: ModuleNotFoundError
> 2021-09-08 05:34:36,789 MainThread polyinterface      ERROR    polyinterface:write: :
> 2021-09-08 05:34:36,789 MainThread polyinterface      ERROR    polyinterface:write: No module named 'pkce'

**Comment by Goose66** [comment]
Looks like at least one of the dependencies needed for the oAuth changes didn’t install (pkce module). You say you got a repo error from Polyglot on the install? What platform are you running Polyglot on?

**Comment by psmith3** [comment]
> Looks like at least one of the dependencies needed for the oAuth changes didn’t install (pkce module). You say you got a repo error from Polyglot on the install? What platform are you running Polyglot on?

I am running, Version 2.2.11, Frontend Version: 2.2.9-5, ISY Version: 5.3.0. I just deleted the MyQ folder manually and reinstalled it through the node server store and get “ cloneRepo: Error: runInstallProcess: undefined”.

**Comment by Goose66** [comment]
First, to be sure, you aren't drprm1 on the UDI forums, are you?

**Comment by Goose66** [comment]
Also, if you deleted the MyQ folder on your Polisy, I am assuming you have SSH access. Go the new MyQ nodeserver folder and run "bash ./install.sh" and see what errors occur.

**Comment by psmith3** [comment]
> Also, if you deleted the MyQ folder on your Polisy, I am assuming you have SSH access. Go the new MyQ nodeserver folder and run "bash ./install.sh" and see what errors occur.

This is not Polisy, but rather a docker image on my Synology NAS that I built back in February. Has been working well since then until now. I'm not sure what is missing or out-of-date. Maybe I missed a dependency in my Docker build. Looks like an issue with lxml.  Here is what I am seeing initially after running ./install.sh

                                                                                                                                                                                                                                       
bash-5.0# ./install.sh                                                                                                                                                                                                                                                              
Requirement already satisfied: polyinterface>=2.1.0 in /root/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.1.0)                                                                                                                                         
Requirement already satisfied: requests>=2.22.0 in /root/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.25.1)                                                                                                                                            
Collecting pkce>=1.0.3                                                                                                                                                                                                                                                              
  Using cached pkce-1.0.3-py3-none-any.whl (3.2 kB)                                                                                                                                                                                                                                 
Collecting pyquery>=1.4.3                                                                                                                                                                                                                                                           
  Using cached pyquery-1.4.3-py3-none-any.whl (22 kB)                                                                                                                                                                                                                               
Requirement already satisfied: markdown2 in /root/.local/lib/python3.8/site-packages (from polyinterface>=2.1.0->-r requirements.txt (line 1)) (2.4.0)                                                                                                                              
Requirement already satisfied: netifaces in /root/.local/lib/python3.8/site-packages (from polyinterface>=2.1.0->-r requirements.txt (line 1)) (0.10.9)                                                                                                                             
Requirement already satisfied: paho-mqtt in /root/.local/lib/python3.8/site-packages (from polyinterface>=2.1.0->-r requirements.txt (line 1)) (1.5.1)                                                                                                                              
Requirement already satisfied: python-dotenv in /root/.local/lib/python3.8/site-packages (from polyinterface>=2.1.0->-r requirements.txt (line 1)) (0.15.0)                                                                                                                         
Requirement already satisfied: idna<3,>=2.5 in /root/.local/lib/python3.8/site-packages (from requests>=2.22.0->-r requirements.txt (line 2)) (2.10)                                                                                                                                
Requirement already satisfied: certifi>=2017.4.17 in /root/.local/lib/python3.8/site-packages (from requests>=2.22.0->-r requirements.txt (line 2)) (2020.12.5)                                                                                                                     
Requirement already satisfied: chardet<5,>=3.0.2 in /root/.local/lib/python3.8/site-packages (from requests>=2.22.0->-r requirements.txt (line 2)) (3.0.4)                                                                                                                          
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/.local/lib/python3.8/site-packages (from requests>=2.22.0->-r requirements.txt (line 2)) (1.26.4)                                                                                                                     
Collecting lxml>=2.1                                                                                                                                                                                                                                                                
  Using cached lxml-4.6.3.tar.gz (3.2 MB)                                                                                                                                                                                                                                           
    ERROR: Command errored out with exit status 1:                                                                                                                                                                                                                                  
     command: /usr/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-on_mlt1z/lxml_e063247a4c34451a81d76736a4cf513e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-on_mlt1z/lxml_e063247a4c34451a81d76736a4cf513e/setup.py'"'"';f = get
attr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp
/pip-pip-egg-info-n3srwf7u                                                                                                                                                                                                                                                          
         cwd: /tmp/pip-install-on_mlt1z/lxml_e063247a4c34451a81d76736a4cf513e/                                                                                                                                                                                                      
    Complete output (3 lines):                                                                                                                                                                                                                                                      
    Building lxml version 4.6.3.                                                                                                                                                                                                                                                    
    Building without Cython.                                                                                                                                                                                                                                                        
    Error: Please make sure the libxml2 and libxslt development packages are installed.                                                                                                                                                                                             
    ----------------------------------------                                                                                                                                                                                                                                        
WARNING: Discarding https://files.pythonhosted.org/packages/e5/21/a2e4517e3d216f0051687eea3d3317557bde68736f038a3b105ac3809247/lxml-4.6.3.tar.gz#sha256=39b78571b3b30645ac77b95f7c69d1bffc4cf8c3b157c435a34da72e78c82468 (from https://pypi.org/simple/lxml/) (requires-python:>=2.7
, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                                                                                                                           
  Using cached lxml-4.6.2.tar.gz (3.2 MB)                                                                                                                                                                                                                                           
    ERROR: Command errored out with exit status 1:                                                                                                                                                                                                                                  
     command: /usr/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-on_mlt1z/lxml_3694803f13174da792890768aaed522a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-on_mlt1z/lxml_3694803f13174da792890768aaed522a/setup.py'"'"';f = get
attr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp
/pip-pip-egg-info-vqrm46d0                                                                                                                                                                                                                                                          
         cwd: /tmp/pip-install-on_mlt1z/lxml_3694803f13174da792890768aaed522a/                                                                                                                                                                                                      
    Complete output (3 lines):                                                                                                                                                                                                                                                      
    Building lxml version 4.6.2.                                                                                                                                                                                                                                                    
    Building without Cython.                                                                                                                                                                                                                                                        
    Error: Please make sure the libxml2 and libxslt development packages are installed.                                                                                                                                                                                             
    ----------------------------------------                                                                                                                                                                                                                                        
WARNING: Discarding https://files.pythonhosted.org/packages/db/f7/43fecb94d66959c1e23aa53d6161231dca0e93ec500224cf31b3c4073e37/lxml-4.6.2.tar.gz#sha256=cd11c7e8d21af997ee8079037fff88f16fda188a9776eb4b81c7e4c9c0a7d7fc (from https://pypi.org/simple/lxml/) (requires-python:>=2.7
, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                                                                                                                           
  Using cached lxml-4.6.1.tar.gz (3.2 MB)                                                                                                                                                                                                                                           
    ERROR: Command errored out with exit status 1:                                                                                                                                                                                                                                  
     command: /usr/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-on_mlt1z/lxml_d5e8589fa74f4680abb60fc7dab39357/setup.py'"'"'; __file__='"'"'/tmp/pip-install-on_mlt1z/lxml_d5e8589fa74f4680abb60fc7dab39357/setup.py'"'"';f = get
attr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp
/pip-pip-egg-info-8b40ai5j                                                                                                                                                                                                                                                          
         cwd: /tmp/pip-install-on_mlt1z/lxml_d5e8589fa74f4680abb60fc7dab39357/                                                                                                                                                                                                      
    Complete output (3 lines):                                                                                                                                                                                                                                                      
    Building lxml version 4.6.1.                                                                                                                                                                                                                                                    
    Building without Cython.                                                                                                                                                                                                                                                        
    Error: Please make sure the libxml2 and libxslt development packages are installed.                                                                                                                                                                                             
    ----------------------------------------                                                                                                                                                                                                                                        
WARNING: Discarding https://files.pythonhosted.org/packages/c5/2f/a0d8aa3eee6d53d5723d89e1fc32eee11e76801b424e30b55c7aa6302b01/lxml-4.6.1.tar.gz#sha256=c152b2e93b639d1f36ec5a8ca24cde4a8eefb2b6b83668fcd8e83a67badcb367 (from https://pypi.org/simple/lxml/) (requires-python:>=2.7
, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                                                                                                                           
  Using cached lxml-4.6.0.tar.gz (3.2 MB)

**Comment by Goose66** [comment]
Looks like you are missing the libxml2 and libxslt application packages in your build. These are required by the lxml module, which is a dependency of pyquery. There is a Polisy user missing these as well, but my Polisy had them installed, and I have heard from a couple of other users that the upgrade went well. 

I did have to install the libxslt1-dev package on my development RPi running buster to get the initial revision of this nodeserver to run. Not sure what OS is running in the docker image, but can you try manually installing either libxml2 and libxslt (as in Polisy) or libxslt1-dev (as in RPi Buster) and see if the "bash ./install.sh" works after that?

**Comment by psmith3** [comment]
> Looks like you are missing the libxml2 and libxslt application packages in your build. These are required by the lxml module, which is a dependency of pyquery. There is a Polisy user missing these as well, but my Polisy had them installed, and I have heard from a couple of other users that the upgrade went well.
> 
> I did have to install the libxslt1-dev package on my development RPi running buster to get the initial revision of this nodeserver to run. Not sure what OS is running in the docker image, but can you try manually installing either libxml2 and libxslt (as in Polisy) or libxslt1-dev (as in RPi Buster) and see if the "bash ./install.sh" works after that?

Here is what I am setting up in my Docker. Is is using Node:10-Alpine. Let me see what the command is the install libxml2 and see if that will fix it. Thanks for the tips!

`FROM node:10-alpine

EXPOSE 3000
EXPOSE 3001

WORKDIR /opt/polyglot-v2/

COPY package.json /opt/polyglot-v2
COPY package.json /opt
COPY package-lock.json /opt
COPY package-lock.json /opt/polyglot-v2

RUN	apk add --no-cache linux-headers build-base && \
		apk add --no-cache python3 python3-dev py3-pip bash git ca-certificates wget tzdata openssl && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    rm -r /root/.cache && \
    cd /opt && \
    git clone --depth=1 --single-branch --branch master https://github.com/UniversalDevicesInc/polyglot-v2.git && \
    npm install

VOLUME /root/.polyglot
VOLUME /usr/lib/python3.8/site-packages

# Run Polyglot
CMD npm start`

**Comment by Goose66** [comment]
libxml2 and libxslt - both are needed, I believe.

**Comment by psmith3** [comment]
> libxml2 and libxslt - both are needed, I believe.

Indeed. Found that about the time you sent this message. Ok. after installing libxlm2 and libxslt, it indeed does install and does authenticate after loading. I logged back into my ISY and rediscovered my doors. BTW, why do I need to manually discover my doors rather than have the node server do it automatically? Thanks for all the help. 

I will need to update my dockerfile to include the following. 

> apk add --update --no-cache --virtual .build-deps g++ gcc libxml2-dev libxslt-dev python-dev && \
   apk add --no-cache libxslt && \
   pip install --no-cache-dir lxml>=3.5.0 && \
   apk del .build-deps

**Comment by Goose66** [comment]
> why do I need to manually discover my doors rather than have the node server do it automatically?

This is so you can delete doors or lamp modules you don't want in the ISY Admin Console and not have them reappear every time the nodeserver restarts.

**Comment by psmith3** [comment]
> > why do I need to manually discover my doors rather than have the node server do it automatically?
> 
> This is so you can delete doors or lamp modules you don't want in the ISY Admin Console and not have them reappear every time the nodeserver restarts.

That makes since. Thanks for getting this working again!
